version: "3.8"

services:
  seller_products:
    build: .
    image: seller_products
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    env_file:
      - .env
