"""Created Product Table

Revision ID: 0ceed38fc348
Revises: 
Create Date: 2023-01-02 01:23:21.570792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ceed38fc348'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('available', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.CheckConstraint('price > 0', name='product_price_is_natural_check'),
    sa.CheckConstraint('quantity >= 0', name='product_quantity_is_positive_check'),
    sa.PrimaryKeyConstraint('offer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
