"""Created tables

Revision ID: f86c8643173d
Revises: 
Create Date: 2023-01-02 02:55:34.500035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f86c8643173d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller',
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('seller_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('available', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('price > 0', name='product_price_is_natural_check'),
    sa.CheckConstraint('quantity >= 0', name='product_quantity_is_positive_check'),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.seller_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('offer',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.seller_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('offer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer')
    op.drop_table('product')
    op.drop_table('seller')
    # ### end Alembic commands ###
